### ISSUE TITLE
[ACG Player][2.6.16 ]The application crashes if I click on Black List

### ISSUE THREAD

**Issue by 44asad** [AugustToko/ACG-Player#2] opened 2019-05-24 05:07 UTC
### Expected behavior
The application should not crash when I click "Black List.

### Actual behavior:
The application is crash when I click "Black List option.

### How to reproduce:
* Download the app and open it
* click Naw menu icon
* Then click setting 
* Naw Black List double click and Done option double click.
* see bug
#### Recording Of The Bug:

https://youtu.be/o9iq1_6cdHo

#### Information
App version:v2.6.16
OS:Android 6.0.1
Device:Samsung J5

### Logcat:
<pre><code>05-23 08:35:54.922 30065 30065 E AndroidRuntime: FATAL EXCEPTION: main
05-23 08:35:54.922 30065 30065 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 30065
05-23 08:35:54.922 30065 30065 E AndroidRuntime: android.database.sqlite.SQLiteException: no such table: myblackpath (code 1): , while compiling: DELETE FROM myblackpath
05-23 08:35:54.922 30065 30065 E AndroidRuntime: #################################################################
05-23 08:35:54.922 30065 30065 E AndroidRuntime: Error Code : 1 (SQLITE_ERROR)
05-23 08:35:54.922 30065 30065 E AndroidRuntime: Caused By : SQL(query) error or missing database.
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   (no such table: myblackpath (code 1): , while compiling: DELETE FROM myblackpath)
05-23 08:35:54.922 30065 30065 E AndroidRuntime: #################################################################
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1062)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:627)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1634)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at org.litepal.crud.DeleteHandler.onDeleteAll(SourceFile:156)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at org.litepal.Operator.deleteAll(SourceFile:1281)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at org.litepal.LitePal.deleteAll(SourceFile:927)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.activity.SettingsActivity.a(SourceFile:543)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.activity.SettingsActivity.lambda$uJuK6yCy63tBcyfQeVmyV0X-2DI(SourceFile)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.activity.-$$Lambda$SettingsActivity$uJuK6yCy63tBcyfQeVmyV0X-2DI.onClick(lambda)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at androidx.appcompat.app.AlertController$b.handleMessage(SourceFile:167)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-23 08:35:54.922 30065 30065 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by AugustToko** [comment] 2019-05-24 08:04
**Thank you very much for your issue.**
Due to my negligence, I did not release a new version on the release page.
You can go to this store to download [https://www.coolapk.com/apk/209705](url)
I will update on the release page later.

**Comment by 44asad** [comment] 2019-05-24 09:52
new version  same problem.

**Comment by AugustToko** [comment] 2019-05-24 13:21
This will be fixed in the next version. 

The cause of the crash is that the done button will delete the blacklist data table. 

Clicking on done twice will delete the blacklist data table that does not exist, causing a crash.

**Comment by AugustToko** [comment] 2019-05-26 13:28
This issue has been fixed and you can check it in the new version.

**Closed by AugustToko** 2019-05-26 13:28 UTC
Labels: bug, good first issue
